services:
- docker
env:
  global:
  - GCP_PROJECT_ID=terraform
  - tf_version=0.12.19

branches:
  only:
    - master

before_install:
- openssl aes-256-cbc -K $encrypted_ba8f794f8d33_key -iv $encrypted_ba8f794f8d33_iv -in google-key.json.enc -out google-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=2google-key.json
- gcloud config set project "${GCP_PROJECT_ID}"

# Install  terraform

- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip


install: true # no-op

script:
- |
  set -ex;
  terraform apply --auto-approve